import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, Header
}: Readonly<{
  children: ReactNode, Header: ReactNode
}>) {

  return (
    <html lang="en">
      <body className="root-body">
        <main className="flex relative top-[80px]">
          {children}
        </main>
      </body>
    </html>
  );
}
